/* 
 * BludeltaWebServiceAPI Selfhosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace IO.Swagger.Model
{
  /// <summary>
  ///   ApiIdentifier
  /// </summary>
  [DataContract]
  public class ApiIdentifier : IEquatable<ApiIdentifier>, IValidatableObject
  {
    /// <summary>
    ///   Initializes a new instance of the <see cref="ApiIdentifier" /> class.
    /// </summary>
    [JsonConstructor]
    protected ApiIdentifier()
    {
    }

    /// <summary>
    ///   Initializes a new instance of the <see cref="ApiIdentifier" /> class.
    /// </summary>
    /// <param name="Name">ApiIdentifier name (required).</param>
    /// <param name="Identifier">Identifier (required).</param>
    public ApiIdentifier(string Name = default(string), string Identifier = default(string))
    {
      // to ensure "Name" is required (not null)
      if (Name == null)
        throw new InvalidDataException("Name is a required property for ApiIdentifier and cannot be null");
      this.Name = Name;
      // to ensure "Identifier" is required (not null)
      if (Identifier == null)
        throw new InvalidDataException("Identifier is a required property for ApiIdentifier and cannot be null");
      this.Identifier = Identifier;
    }

    /// <summary>
    ///   ApiIdentifier name
    /// </summary>
    /// <value>ApiIdentifier name</value>
    [DataMember(Name = "Name", EmitDefaultValue = false)]
    public string Name { get; set; }

    /// <summary>
    ///   Identifier
    /// </summary>
    /// <value>Identifier</value>
    [DataMember(Name = "Identifier", EmitDefaultValue = false)]
    public string Identifier { get; set; }

    /// <summary>
    ///   Returns true if ApiIdentifier instances are equal
    /// </summary>
    /// <param name="other">Instance of ApiIdentifier to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ApiIdentifier other)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      if (other == null)
        return false;

      return
        (
          Name == other.Name ||
          Name != null &&
          Name.Equals(other.Name)
        ) &&
        (
          Identifier == other.Identifier ||
          Identifier != null &&
          Identifier.Equals(other.Identifier)
        );
    }

    /// <summary>
    ///   To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      yield break;
    }

    /// <summary>
    ///   Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class ApiIdentifier {\n");
      sb.Append("  Name: ").Append(Name).Append("\n");
      sb.Append("  Identifier: ").Append(Identifier).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    ///   Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///   Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      return Equals(obj as ApiIdentifier);
    }

    /// <summary>
    ///   Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      // credit: http://stackoverflow.com/a/263416/677735
      unchecked // Overflow is fine, just wrap
      {
        var hash = 41;
        // Suitable nullity checks etc, of course :)
        if (Name != null)
          hash = hash * 59 + Name.GetHashCode();
        if (Identifier != null)
          hash = hash * 59 + Identifier.GetHashCode();
        return hash;
      }
    }
  }
}