/* 
 * BludeltaWebServiceAPI Selfhosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace IO.Swagger.Model
{
  /// <summary>
  ///   Get an image of one page. Either a thumbnail or a high resolution images
  /// </summary>
  [DataContract]
  public class ImageRequest : IEquatable<ImageRequest>, IValidatableObject
  {
    /// <summary>
    ///   Initializes a new instance of the <see cref="ImageRequest" /> class.
    /// </summary>
    [JsonConstructor]
    protected ImageRequest()
    {
    }

    /// <summary>
    ///   Initializes a new instance of the <see cref="ImageRequest" /> class.
    /// </summary>
    /// <param name="Id">Image id (required).</param>
    public ImageRequest(string Id = default(string))
    {
      // to ensure "Id" is required (not null)
      if (Id == null)
        throw new InvalidDataException("Id is a required property for ImageRequest and cannot be null");
      this.Id = Id;
    }

    /// <summary>
    ///   Image id
    /// </summary>
    /// <value>Image id</value>
    [DataMember(Name = "Id", EmitDefaultValue = false)]
    public string Id { get; set; }

    /// <summary>
    ///   Returns true if ImageRequest instances are equal
    /// </summary>
    /// <param name="other">Instance of ImageRequest to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ImageRequest other)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      if (other == null)
        return false;

      return
        Id == other.Id ||
        Id != null &&
        Id.Equals(other.Id);
    }

    /// <summary>
    ///   To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      yield break;
    }

    /// <summary>
    ///   Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class ImageRequest {\n");
      sb.Append("  Id: ").Append(Id).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    ///   Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///   Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      return Equals(obj as ImageRequest);
    }

    /// <summary>
    ///   Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      // credit: http://stackoverflow.com/a/263416/677735
      unchecked // Overflow is fine, just wrap
      {
        var hash = 41;
        // Suitable nullity checks etc, of course :)
        if (Id != null)
          hash = hash * 59 + Id.GetHashCode();
        return hash;
      }
    }
  }
}