/* 
 * BludeltaWebServiceAPI Selfhosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace IO.Swagger.Model
{
  /// <summary>
  ///   InvoiceContainerSaveResponse
  /// </summary>
  [DataContract]
  public class InvoiceContainerSaveResponse : IEquatable<InvoiceContainerSaveResponse>, IValidatableObject
  {
    /// <summary>
    ///   Initializes a new instance of the <see cref="InvoiceContainerSaveResponse" /> class.
    /// </summary>
    /// <param name="State">State.</param>
    /// <param name="Message">Error message in case of an error.</param>
    /// <param name="InvoiceContainer">InvoiceContainer.</param>
    public InvoiceContainerSaveResponse(int? State = default(int?), string Message = default(string),
      InvoiceContainer InvoiceContainer = default(InvoiceContainer))
    {
      this.State = State;
      this.Message = Message;
      this.InvoiceContainer = InvoiceContainer;
    }

    /// <summary>
    ///   Gets or Sets State
    /// </summary>
    [DataMember(Name = "State", EmitDefaultValue = false)]
    public int? State { get; set; }

    /// <summary>
    ///   Error message in case of an error
    /// </summary>
    /// <value>Error message in case of an error</value>
    [DataMember(Name = "Message", EmitDefaultValue = false)]
    public string Message { get; set; }

    /// <summary>
    ///   Gets or Sets InvoiceContainer
    /// </summary>
    [DataMember(Name = "InvoiceContainer", EmitDefaultValue = false)]
    public InvoiceContainer InvoiceContainer { get; set; }

    /// <summary>
    ///   Returns true if InvoiceContainerSaveResponse instances are equal
    /// </summary>
    /// <param name="other">Instance of InvoiceContainerSaveResponse to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(InvoiceContainerSaveResponse other)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      if (other == null)
        return false;

      return
        (
          State == other.State ||
          State != null &&
          State.Equals(other.State)
        ) &&
        (
          Message == other.Message ||
          Message != null &&
          Message.Equals(other.Message)
        ) &&
        (
          InvoiceContainer == other.InvoiceContainer ||
          InvoiceContainer != null &&
          InvoiceContainer.Equals(other.InvoiceContainer)
        );
    }

    /// <summary>
    ///   To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      yield break;
    }

    /// <summary>
    ///   Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class InvoiceContainerSaveResponse {\n");
      sb.Append("  State: ").Append(State).Append("\n");
      sb.Append("  Message: ").Append(Message).Append("\n");
      sb.Append("  InvoiceContainer: ").Append(InvoiceContainer).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    ///   Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///   Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      return Equals(obj as InvoiceContainerSaveResponse);
    }

    /// <summary>
    ///   Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      // credit: http://stackoverflow.com/a/263416/677735
      unchecked // Overflow is fine, just wrap
      {
        var hash = 41;
        // Suitable nullity checks etc, of course :)
        if (State != null)
          hash = hash * 59 + State.GetHashCode();
        if (Message != null)
          hash = hash * 59 + Message.GetHashCode();
        if (InvoiceContainer != null)
          hash = hash * 59 + InvoiceContainer.GetHashCode();
        return hash;
      }
    }
  }
}