/* 
 * BludeltaWebServiceAPI Selfhosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace IO.Swagger.Model
{
  /// <summary>
  ///   Since the lock of a container has a timeout, the GUI has to send cyclic keep alive messages in order to reset the
  ///   timeout counter of the lock.
  /// </summary>
  [DataContract]
  public class InvoiceContainerKeepAliveLockRequest : IEquatable<InvoiceContainerKeepAliveLockRequest>,
    IValidatableObject
  {
    /// <summary>
    ///   Initializes a new instance of the <see cref="InvoiceContainerKeepAliveLockRequest" /> class.
    /// </summary>
    /// <param name="ContainerId">ContainerId.</param>
    /// <param name="TimeoutSeconds">TimeoutSeconds.</param>
    public InvoiceContainerKeepAliveLockRequest(string ContainerId = default(string),
      int? TimeoutSeconds = default(int?))
    {
      this.ContainerId = ContainerId;
      this.TimeoutSeconds = TimeoutSeconds;
    }

    /// <summary>
    ///   Gets or Sets ContainerId
    /// </summary>
    [DataMember(Name = "ContainerId", EmitDefaultValue = false)]
    public string ContainerId { get; set; }

    /// <summary>
    ///   Gets or Sets TimeoutSeconds
    /// </summary>
    [DataMember(Name = "TimeoutSeconds", EmitDefaultValue = false)]
    public int? TimeoutSeconds { get; set; }

    /// <summary>
    ///   Returns true if InvoiceContainerKeepAliveLockRequest instances are equal
    /// </summary>
    /// <param name="other">Instance of InvoiceContainerKeepAliveLockRequest to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(InvoiceContainerKeepAliveLockRequest other)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      if (other == null)
        return false;

      return
        (
          ContainerId == other.ContainerId ||
          ContainerId != null &&
          ContainerId.Equals(other.ContainerId)
        ) &&
        (
          TimeoutSeconds == other.TimeoutSeconds ||
          TimeoutSeconds != null &&
          TimeoutSeconds.Equals(other.TimeoutSeconds)
        );
    }

    /// <summary>
    ///   To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      yield break;
    }

    /// <summary>
    ///   Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class InvoiceContainerKeepAliveLockRequest {\n");
      sb.Append("  ContainerId: ").Append(ContainerId).Append("\n");
      sb.Append("  TimeoutSeconds: ").Append(TimeoutSeconds).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    ///   Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///   Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      return Equals(obj as InvoiceContainerKeepAliveLockRequest);
    }

    /// <summary>
    ///   Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      // credit: http://stackoverflow.com/a/263416/677735
      unchecked // Overflow is fine, just wrap
      {
        var hash = 41;
        // Suitable nullity checks etc, of course :)
        if (ContainerId != null)
          hash = hash * 59 + ContainerId.GetHashCode();
        if (TimeoutSeconds != null)
          hash = hash * 59 + TimeoutSeconds.GetHashCode();
        return hash;
      }
    }
  }
}