/* 
 * BludeltaWebServiceAPI Selfhosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace IO.Swagger.Model
{
  /// <summary>
  ///   InvoiceContainersResponse
  /// </summary>
  [DataContract]
  public class InvoiceContainersResponse : IEquatable<InvoiceContainersResponse>, IValidatableObject
  {
    /// <summary>
    ///   Initializes a new instance of the <see cref="InvoiceContainersResponse" /> class.
    /// </summary>
    [JsonConstructor]
    protected InvoiceContainersResponse()
    {
    }

    /// <summary>
    ///   Initializes a new instance of the <see cref="InvoiceContainersResponse" /> class.
    /// </summary>
    /// <param name="State">On success state &#x3D;&#x3D; 0 else state &gt; 0 (required).</param>
    /// <param name="From">From.</param>
    /// <param name="To">To.</param>
    /// <param name="InvoiceContainers">InvoiceContainers.</param>
    public InvoiceContainersResponse(int? State = default(int?), DateTime? From = default(DateTime?),
      DateTime? To = default(DateTime?), List<InvoiceContainer> InvoiceContainers = default(List<InvoiceContainer>))
    {
      // to ensure "State" is required (not null)
      if (State == null)
        throw new InvalidDataException("State is a required property for InvoiceContainersResponse and cannot be null");
      this.State = State;
      this.From = From;
      this.To = To;
      this.InvoiceContainers = InvoiceContainers;
    }

    /// <summary>
    ///   On success state &#x3D;&#x3D; 0 else state &gt; 0
    /// </summary>
    /// <value>On success state &#x3D;&#x3D; 0 else state &gt; 0</value>
    [DataMember(Name = "State", EmitDefaultValue = false)]
    public int? State { get; set; }

    /// <summary>
    ///   Gets or Sets From
    /// </summary>
    [DataMember(Name = "From", EmitDefaultValue = false)]
    public DateTime? From { get; set; }

    /// <summary>
    ///   Gets or Sets To
    /// </summary>
    [DataMember(Name = "To", EmitDefaultValue = false)]
    public DateTime? To { get; set; }

    /// <summary>
    ///   Gets or Sets InvoiceContainers
    /// </summary>
    [DataMember(Name = "InvoiceContainers", EmitDefaultValue = false)]
    public List<InvoiceContainer> InvoiceContainers { get; set; }

    /// <summary>
    ///   Returns true if InvoiceContainersResponse instances are equal
    /// </summary>
    /// <param name="other">Instance of InvoiceContainersResponse to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(InvoiceContainersResponse other)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      if (other == null)
        return false;

      return
        (
          State == other.State ||
          State != null &&
          State.Equals(other.State)
        ) &&
        (
          From == other.From ||
          From != null &&
          From.Equals(other.From)
        ) &&
        (
          To == other.To ||
          To != null &&
          To.Equals(other.To)
        ) &&
        (
          InvoiceContainers == other.InvoiceContainers ||
          InvoiceContainers != null &&
          InvoiceContainers.SequenceEqual(other.InvoiceContainers)
        );
    }

    /// <summary>
    ///   To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      yield break;
    }

    /// <summary>
    ///   Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class InvoiceContainersResponse {\n");
      sb.Append("  State: ").Append(State).Append("\n");
      sb.Append("  From: ").Append(From).Append("\n");
      sb.Append("  To: ").Append(To).Append("\n");
      sb.Append("  InvoiceContainers: ").Append(InvoiceContainers).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    ///   Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///   Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      return Equals(obj as InvoiceContainersResponse);
    }

    /// <summary>
    ///   Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      // credit: http://stackoverflow.com/a/263416/677735
      unchecked // Overflow is fine, just wrap
      {
        var hash = 41;
        // Suitable nullity checks etc, of course :)
        if (State != null)
          hash = hash * 59 + State.GetHashCode();
        if (From != null)
          hash = hash * 59 + From.GetHashCode();
        if (To != null)
          hash = hash * 59 + To.GetHashCode();
        if (InvoiceContainers != null)
          hash = hash * 59 + InvoiceContainers.GetHashCode();
        return hash;
      }
    }
  }
}