/* 
 * BludeltaWebServiceAPI Selfhosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace IO.Swagger.Model
{
  /// <summary>
  ///   Page
  /// </summary>
  [DataContract]
  public class Page : IEquatable<Page>, IValidatableObject
  {
    /// <summary>
    ///   Initializes a new instance of the <see cref="Page" /> class.
    /// </summary>
    /// <param name="PageNo">PageNo.</param>
    /// <param name="PreviewSrc">PreviewSrc.</param>
    /// <param name="Src">Src.</param>
    public Page(int? PageNo = default(int?), string PreviewSrc = default(string), string Src = default(string))
    {
      this.PageNo = PageNo;
      this.PreviewSrc = PreviewSrc;
      this.Src = Src;
    }

    /// <summary>
    ///   Gets or Sets PageNo
    /// </summary>
    [DataMember(Name = "PageNo", EmitDefaultValue = false)]
    public int? PageNo { get; set; }

    /// <summary>
    ///   Gets or Sets PreviewSrc
    /// </summary>
    [DataMember(Name = "PreviewSrc", EmitDefaultValue = false)]
    public string PreviewSrc { get; set; }

    /// <summary>
    ///   Gets or Sets Src
    /// </summary>
    [DataMember(Name = "Src", EmitDefaultValue = false)]
    public string Src { get; set; }

    /// <summary>
    ///   Returns true if Page instances are equal
    /// </summary>
    /// <param name="other">Instance of Page to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Page other)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      if (other == null)
        return false;

      return
        (
          PageNo == other.PageNo ||
          PageNo != null &&
          PageNo.Equals(other.PageNo)
        ) &&
        (
          PreviewSrc == other.PreviewSrc ||
          PreviewSrc != null &&
          PreviewSrc.Equals(other.PreviewSrc)
        ) &&
        (
          Src == other.Src ||
          Src != null &&
          Src.Equals(other.Src)
        );
    }

    /// <summary>
    ///   To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      yield break;
    }

    /// <summary>
    ///   Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class Page {\n");
      sb.Append("  PageNo: ").Append(PageNo).Append("\n");
      sb.Append("  PreviewSrc: ").Append(PreviewSrc).Append("\n");
      sb.Append("  Src: ").Append(Src).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    ///   Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///   Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      return Equals(obj as Page);
    }

    /// <summary>
    ///   Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      // credit: http://stackoverflow.com/a/263416/677735
      unchecked // Overflow is fine, just wrap
      {
        var hash = 41;
        // Suitable nullity checks etc, of course :)
        if (PageNo != null)
          hash = hash * 59 + PageNo.GetHashCode();
        if (PreviewSrc != null)
          hash = hash * 59 + PreviewSrc.GetHashCode();
        if (Src != null)
          hash = hash * 59 + Src.GetHashCode();
        return hash;
      }
    }
  }
}