/* 
 * BludeltaWebServiceAPI Selfhosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace IO.Swagger.Model
{
  /// <summary>
  ///   ReleasableInvoiceResponse
  /// </summary>
  [DataContract]
  public class ReleasableInvoiceResponse : IEquatable<ReleasableInvoiceResponse>, IValidatableObject
  {
    /// <summary>
    ///   Initializes a new instance of the <see cref="ReleasableInvoiceResponse" /> class.
    /// </summary>
    [JsonConstructor]
    protected ReleasableInvoiceResponse()
    {
    }

    /// <summary>
    ///   Initializes a new instance of the <see cref="ReleasableInvoiceResponse" /> class.
    /// </summary>
    /// <param name="State">On success state &#x3D;&#x3D; 0 else state &gt; 0 (required).</param>
    /// <param name="Invoices">An array of releasable invoices.</param>
    public ReleasableInvoiceResponse(int? State = default(int?),
      List<ReleasableInvoice> Invoices = default(List<ReleasableInvoice>))
    {
      // to ensure "State" is required (not null)
      if (State == null)
        throw new InvalidDataException("State is a required property for ReleasableInvoiceResponse and cannot be null");
      this.State = State;
      this.Invoices = Invoices;
    }

    /// <summary>
    ///   On success state &#x3D;&#x3D; 0 else state &gt; 0
    /// </summary>
    /// <value>On success state &#x3D;&#x3D; 0 else state &gt; 0</value>
    [DataMember(Name = "State", EmitDefaultValue = false)]
    public int? State { get; set; }

    /// <summary>
    ///   An array of releasable invoices
    /// </summary>
    /// <value>An array of releasable invoices</value>
    [DataMember(Name = "Invoices", EmitDefaultValue = false)]
    public List<ReleasableInvoice> Invoices { get; set; }

    /// <summary>
    ///   Returns true if ReleasableInvoiceResponse instances are equal
    /// </summary>
    /// <param name="other">Instance of ReleasableInvoiceResponse to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ReleasableInvoiceResponse other)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      if (other == null)
        return false;

      return
        (
          State == other.State ||
          State != null &&
          State.Equals(other.State)
        ) &&
        (
          Invoices == other.Invoices ||
          Invoices != null &&
          Invoices.SequenceEqual(other.Invoices)
        );
    }

    /// <summary>
    ///   To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      yield break;
    }

    /// <summary>
    ///   Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class ReleasableInvoiceResponse {\n");
      sb.Append("  State: ").Append(State).Append("\n");
      sb.Append("  Invoices: ").Append(Invoices).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    ///   Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///   Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      return Equals(obj as ReleasableInvoiceResponse);
    }

    /// <summary>
    ///   Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      // credit: http://stackoverflow.com/a/263416/677735
      unchecked // Overflow is fine, just wrap
      {
        var hash = 41;
        // Suitable nullity checks etc, of course :)
        if (State != null)
          hash = hash * 59 + State.GetHashCode();
        if (Invoices != null)
          hash = hash * 59 + Invoices.GetHashCode();
        return hash;
      }
    }
  }
}