/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Releases invoices. Ready for import
    /// </summary>
    [DataContract]
    public partial class ReleaseInvoiceRequest :  IEquatable<ReleaseInvoiceRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseInvoiceRequest" /> class.
        /// </summary>
        /// <param name="InvoiceIds">InvoiceIds.</param>
        public ReleaseInvoiceRequest(List<string> InvoiceIds = default(List<string>))
        {
            this.InvoiceIds = InvoiceIds;
        }
        
        /// <summary>
        /// Gets or Sets InvoiceIds
        /// </summary>
        [DataMember(Name="InvoiceIds", EmitDefaultValue=false)]
        public List<string> InvoiceIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReleaseInvoiceRequest {\n");
            sb.Append("  InvoiceIds: ").Append(InvoiceIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ReleaseInvoiceRequest);
        }

        /// <summary>
        /// Returns true if ReleaseInvoiceRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ReleaseInvoiceRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReleaseInvoiceRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.InvoiceIds == other.InvoiceIds ||
                    this.InvoiceIds != null &&
                    this.InvoiceIds.SequenceEqual(other.InvoiceIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.InvoiceIds != null)
                    hash = hash * 59 + this.InvoiceIds.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
