/* 
 * BludeltaWebServiceAPI Selfhosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace IO.Swagger.Model
{
  /// <summary>
  ///   Saves an invoice.
  /// </summary>
  [DataContract]
  public class SaveInvoiceRequest : IEquatable<SaveInvoiceRequest>, IValidatableObject
  {
    /// <summary>
    ///   Initializes a new instance of the <see cref="SaveInvoiceRequest" /> class.
    /// </summary>
    /// <param name="ContainerId">ContainerId.</param>
    /// <param name="Invoice">Invoice.</param>
    public SaveInvoiceRequest(string ContainerId = default(string), Invoice Invoice = default(Invoice))
    {
      this.ContainerId = ContainerId;
      this.Invoice = Invoice;
    }

    /// <summary>
    ///   Gets or Sets ContainerId
    /// </summary>
    [DataMember(Name = "ContainerId", EmitDefaultValue = false)]
    public string ContainerId { get; set; }

    /// <summary>
    ///   Gets or Sets Invoice
    /// </summary>
    [DataMember(Name = "Invoice", EmitDefaultValue = false)]
    public Invoice Invoice { get; set; }

    /// <summary>
    ///   Returns true if SaveInvoiceRequest instances are equal
    /// </summary>
    /// <param name="other">Instance of SaveInvoiceRequest to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(SaveInvoiceRequest other)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      if (other == null)
        return false;

      return
        (
          ContainerId == other.ContainerId ||
          ContainerId != null &&
          ContainerId.Equals(other.ContainerId)
        ) &&
        (
          Invoice == other.Invoice ||
          Invoice != null &&
          Invoice.Equals(other.Invoice)
        );
    }

    /// <summary>
    ///   To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      yield break;
    }

    /// <summary>
    ///   Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class SaveInvoiceRequest {\n");
      sb.Append("  ContainerId: ").Append(ContainerId).Append("\n");
      sb.Append("  Invoice: ").Append(Invoice).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    ///   Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///   Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
      // credit: http://stackoverflow.com/a/10454552/677735
      return Equals(obj as SaveInvoiceRequest);
    }

    /// <summary>
    ///   Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      // credit: http://stackoverflow.com/a/263416/677735
      unchecked // Overflow is fine, just wrap
      {
        var hash = 41;
        // Suitable nullity checks etc, of course :)
        if (ContainerId != null)
          hash = hash * 59 + ContainerId.GetHashCode();
        if (Invoice != null)
          hash = hash * 59 + Invoice.GetHashCode();
        return hash;
      }
    }
  }
}