/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing AddressResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class AddressResponseTests
  {
    // TODO uncomment below to declare an instance variable for AddressResponse
    //private AddressResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of AddressResponse
      //instance = new AddressResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of AddressResponse
    /// </summary>
    [Test]
    public void AddressResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" AddressResponse
      //Assert.IsInstanceOfType<AddressResponse> (instance, "variable 'instance' is a AddressResponse");
    }

    /// <summary>
    ///   Test the property 'City'
    /// </summary>
    [Test]
    public void CityTest()
    {
      // TODO unit test for the property 'City'
    }

    /// <summary>
    ///   Test the property 'Country'
    /// </summary>
    [Test]
    public void CountryTest()
    {
      // TODO unit test for the property 'Country'
    }

    /// <summary>
    ///   Test the property 'Height'
    /// </summary>
    [Test]
    public void HeightTest()
    {
      // TODO unit test for the property 'Height'
    }

    /// <summary>
    ///   Test the property 'Street'
    /// </summary>
    [Test]
    public void StreetTest()
    {
      // TODO unit test for the property 'Street'
    }

    /// <summary>
    ///   Test the property 'Width'
    /// </summary>
    [Test]
    public void WidthTest()
    {
      // TODO unit test for the property 'Width'
    }

    /// <summary>
    ///   Test the property 'X'
    /// </summary>
    [Test]
    public void XTest()
    {
      // TODO unit test for the property 'X'
    }

    /// <summary>
    ///   Test the property 'Y'
    /// </summary>
    [Test]
    public void YTest()
    {
      // TODO unit test for the property 'Y'
    }

    /// <summary>
    ///   Test the property 'ZipCode'
    /// </summary>
    [Test]
    public void ZipCodeTest()
    {
      // TODO unit test for the property 'ZipCode'
    }
  }
}