/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing ApiIdentifier
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class ApiIdentifierTests
  {
    // TODO uncomment below to declare an instance variable for ApiIdentifier
    //private ApiIdentifier instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of ApiIdentifier
      //instance = new ApiIdentifier();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of ApiIdentifier
    /// </summary>
    [Test]
    public void ApiIdentifierInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" ApiIdentifier
      //Assert.IsInstanceOfType<ApiIdentifier> (instance, "variable 'instance' is a ApiIdentifier");
    }

    /// <summary>
    ///   Test the property 'Identifier'
    /// </summary>
    [Test]
    public void IdentifierTest()
    {
      // TODO unit test for the property 'Identifier'
    }

    /// <summary>
    ///   Test the property 'Name'
    /// </summary>
    [Test]
    public void NameTest()
    {
      // TODO unit test for the property 'Name'
    }
  }
}