/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing ApiKey
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class ApiKeyTests
  {
    // TODO uncomment below to declare an instance variable for ApiKey
    //private ApiKey instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of ApiKey
      //instance = new ApiKey();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of ApiKey
    /// </summary>
    [Test]
    public void ApiKeyInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" ApiKey
      //Assert.IsInstanceOfType<ApiKey> (instance, "variable 'instance' is a ApiKey");
    }

    /// <summary>
    ///   Test the property 'Key'
    /// </summary>
    [Test]
    public void KeyTest()
    {
      // TODO unit test for the property 'Key'
    }

    /// <summary>
    ///   Test the property 'Name'
    /// </summary>
    [Test]
    public void NameTest()
    {
      // TODO unit test for the property 'Name'
    }
  }
}