/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing ContactResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class ContactResponseTests
  {
    // TODO uncomment below to declare an instance variable for ContactResponse
    //private ContactResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of ContactResponse
      //instance = new ContactResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'Address'
    /// </summary>
    [Test]
    public void AddressTest()
    {
      // TODO unit test for the property 'Address'
    }

    /// <summary>
    ///   Test an instance of ContactResponse
    /// </summary>
    [Test]
    public void ContactResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" ContactResponse
      //Assert.IsInstanceOfType<ContactResponse> (instance, "variable 'instance' is a ContactResponse");
    }

    /// <summary>
    ///   Test the property 'Email'
    /// </summary>
    [Test]
    public void EmailTest()
    {
      // TODO unit test for the property 'Email'
    }

    /// <summary>
    ///   Test the property 'Fax'
    /// </summary>
    [Test]
    public void FaxTest()
    {
      // TODO unit test for the property 'Fax'
    }

    /// <summary>
    ///   Test the property 'Name'
    /// </summary>
    [Test]
    public void NameTest()
    {
      // TODO unit test for the property 'Name'
    }

    /// <summary>
    ///   Test the property 'Phone'
    /// </summary>
    [Test]
    public void PhoneTest()
    {
      // TODO unit test for the property 'Phone'
    }

    /// <summary>
    ///   Test the property 'Score'
    /// </summary>
    [Test]
    public void ScoreTest()
    {
      // TODO unit test for the property 'Score'
    }

    /// <summary>
    ///   Test the property 'WebsiteUrl'
    /// </summary>
    [Test]
    public void WebsiteUrlTest()
    {
      // TODO unit test for the property 'WebsiteUrl'
    }
  }
}