/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing DetailResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class DetailResponseTests
  {
    // TODO uncomment below to declare an instance variable for DetailResponse
    //private DetailResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of DetailResponse
      //instance = new DetailResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of DetailResponse
    /// </summary>
    [Test]
    public void DetailResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" DetailResponse
      //Assert.IsInstanceOfType<DetailResponse> (instance, "variable 'instance' is a DetailResponse");
    }

    /// <summary>
    ///   Test the property 'Height'
    /// </summary>
    [Test]
    public void HeightTest()
    {
      // TODO unit test for the property 'Height'
    }

    /// <summary>
    ///   Test the property 'Name'
    /// </summary>
    [Test]
    public void NameTest()
    {
      // TODO unit test for the property 'Name'
    }

    /// <summary>
    ///   Test the property 'Score'
    /// </summary>
    [Test]
    public void ScoreTest()
    {
      // TODO unit test for the property 'Score'
    }

    /// <summary>
    ///   Test the property 'Text'
    /// </summary>
    [Test]
    public void TextTest()
    {
      // TODO unit test for the property 'Text'
    }

    /// <summary>
    ///   Test the property 'Value'
    /// </summary>
    [Test]
    public void ValueTest()
    {
      // TODO unit test for the property 'Value'
    }

    /// <summary>
    ///   Test the property 'Width'
    /// </summary>
    [Test]
    public void WidthTest()
    {
      // TODO unit test for the property 'Width'
    }

    /// <summary>
    ///   Test the property 'X'
    /// </summary>
    [Test]
    public void XTest()
    {
      // TODO unit test for the property 'X'
    }

    /// <summary>
    ///   Test the property 'Y'
    /// </summary>
    [Test]
    public void YTest()
    {
      // TODO unit test for the property 'Y'
    }
  }
}