/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing DetectInvoiceResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class DetectInvoiceResponseTests
  {
    // TODO uncomment below to declare an instance variable for DetectInvoiceResponse
    //private DetectInvoiceResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of DetectInvoiceResponse
      //instance = new DetectInvoiceResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of DetectInvoiceResponse
    /// </summary>
    [Test]
    public void DetectInvoiceResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" DetectInvoiceResponse
      //Assert.IsInstanceOfType<DetectInvoiceResponse> (instance, "variable 'instance' is a DetectInvoiceResponse");
    }

    /// <summary>
    ///   Test the property 'DocumentResolution'
    /// </summary>
    [Test]
    public void DocumentResolutionTest()
    {
      // TODO unit test for the property 'DocumentResolution'
    }

    /// <summary>
    ///   Test the property 'FormattedResult'
    /// </summary>
    [Test]
    public void FormattedResultTest()
    {
      // TODO unit test for the property 'FormattedResult'
    }

    /// <summary>
    ///   Test the property 'InvoiceDetailTypePredictions'
    /// </summary>
    [Test]
    public void InvoiceDetailTypePredictionsTest()
    {
      // TODO unit test for the property 'InvoiceDetailTypePredictions'
    }

    /// <summary>
    ///   Test the property 'InvoiceState'
    /// </summary>
    [Test]
    public void InvoiceStateTest()
    {
      // TODO unit test for the property 'InvoiceState'
    }

    /// <summary>
    ///   Test the property 'IsQualityOk'
    /// </summary>
    [Test]
    public void IsQualityOkTest()
    {
      // TODO unit test for the property 'IsQualityOk'
    }

    /// <summary>
    ///   Test the property 'Language'
    /// </summary>
    [Test]
    public void LanguageTest()
    {
      // TODO unit test for the property 'Language'
    }

    /// <summary>
    ///   Test the property 'LineItems'
    /// </summary>
    [Test]
    public void LineItemsTest()
    {
      // TODO unit test for the property 'LineItems'
    }

    /// <summary>
    ///   Test the property 'Measurements'
    /// </summary>
    [Test]
    public void MeasurementsTest()
    {
      // TODO unit test for the property 'Measurements'
    }

    /// <summary>
    ///   Test the property 'OcrResult'
    /// </summary>
    [Test]
    public void OcrResultTest()
    {
      // TODO unit test for the property 'OcrResult'
    }

    /// <summary>
    ///   Test the property 'PredictionGroups'
    /// </summary>
    [Test]
    public void PredictionGroupsTest()
    {
      // TODO unit test for the property 'PredictionGroups'
    }

    /// <summary>
    ///   Test the property 'ResultPdf'
    /// </summary>
    [Test]
    public void ResultPdfTest()
    {
      // TODO unit test for the property 'ResultPdf'
    }

    /// <summary>
    ///   Test the property 'Sender'
    /// </summary>
    [Test]
    public void SenderTest()
    {
      // TODO unit test for the property 'Sender'
    }
  }
}