/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing DetectionResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class DetectionResponseTests
  {
    // TODO uncomment below to declare an instance variable for DetectionResponse
    //private DetectionResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of DetectionResponse
      //instance = new DetectionResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of DetectionResponse
    /// </summary>
    [Test]
    public void DetectionResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" DetectionResponse
      //Assert.IsInstanceOfType<DetectionResponse> (instance, "variable 'instance' is a DetectionResponse");
    }

    /// <summary>
    ///   Test the property 'Height'
    /// </summary>
    [Test]
    public void HeightTest()
    {
      // TODO unit test for the property 'Height'
    }

    /// <summary>
    ///   Test the property 'Score'
    /// </summary>
    [Test]
    public void ScoreTest()
    {
      // TODO unit test for the property 'Score'
    }

    /// <summary>
    ///   Test the property 'TypeName'
    /// </summary>
    [Test]
    public void TypeNameTest()
    {
      // TODO unit test for the property 'TypeName'
    }

    /// <summary>
    ///   Test the property 'Type'
    /// </summary>
    [Test]
    public void TypeTest()
    {
      // TODO unit test for the property 'Type'
    }

    /// <summary>
    ///   Test the property 'Value'
    /// </summary>
    [Test]
    public void ValueTest()
    {
      // TODO unit test for the property 'Value'
    }

    /// <summary>
    ///   Test the property 'Width'
    /// </summary>
    [Test]
    public void WidthTest()
    {
      // TODO unit test for the property 'Width'
    }

    /// <summary>
    ///   Test the property 'X'
    /// </summary>
    [Test]
    public void XTest()
    {
      // TODO unit test for the property 'X'
    }

    /// <summary>
    ///   Test the property 'Y'
    /// </summary>
    [Test]
    public void YTest()
    {
      // TODO unit test for the property 'Y'
    }
  }
}