/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing DictionaryStringInt64
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class DictionaryStringInt64Tests
  {
    // TODO uncomment below to declare an instance variable for DictionaryStringInt64
    //private DictionaryStringInt64 instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of DictionaryStringInt64
      //instance = new DictionaryStringInt64();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of DictionaryStringInt64
    /// </summary>
    [Test]
    public void DictionaryStringInt64InstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" DictionaryStringInt64
      //Assert.IsInstanceOfType<DictionaryStringInt64> (instance, "variable 'instance' is a DictionaryStringInt64");
    }
  }
}