/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainer
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainerTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainer
    //private InvoiceContainer instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainer
      //instance = new InvoiceContainer();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'ContainerId'
    /// </summary>
    [Test]
    public void ContainerIdTest()
    {
      // TODO unit test for the property 'ContainerId'
    }

    /// <summary>
    ///   Test the property 'CreatedBy'
    /// </summary>
    [Test]
    public void CreatedByTest()
    {
      // TODO unit test for the property 'CreatedBy'
    }

    /// <summary>
    ///   Test the property 'Created'
    /// </summary>
    [Test]
    public void CreatedTest()
    {
      // TODO unit test for the property 'Created'
    }

    /// <summary>
    ///   Test an instance of InvoiceContainer
    /// </summary>
    [Test]
    public void InvoiceContainerInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainer
      //Assert.IsInstanceOfType<InvoiceContainer> (instance, "variable 'instance' is a InvoiceContainer");
    }

    /// <summary>
    ///   Test the property 'Invoices'
    /// </summary>
    [Test]
    public void InvoicesTest()
    {
      // TODO unit test for the property 'Invoices'
    }

    /// <summary>
    ///   Test the property 'Name'
    /// </summary>
    [Test]
    public void NameTest()
    {
      // TODO unit test for the property 'Name'
    }
  }
}