/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainerSaveRequest
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainerSaveRequestTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainerSaveRequest
    //private InvoiceContainerSaveRequest instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainerSaveRequest
      //instance = new InvoiceContainerSaveRequest();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'ContainerId'
    /// </summary>
    [Test]
    public void ContainerIdTest()
    {
      // TODO unit test for the property 'ContainerId'
    }

    /// <summary>
    ///   Test an instance of InvoiceContainerSaveRequest
    /// </summary>
    [Test]
    public void InvoiceContainerSaveRequestInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainerSaveRequest
      //Assert.IsInstanceOfType<InvoiceContainerSaveRequest> (instance, "variable 'instance' is a InvoiceContainerSaveRequest");
    }

    /// <summary>
    ///   Test the property 'InvoiceContainer'
    /// </summary>
    [Test]
    public void InvoiceContainerTest()
    {
      // TODO unit test for the property 'InvoiceContainer'
    }
  }
}