/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainerRequest
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainerRequestTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainerRequest
    //private InvoiceContainerRequest instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainerRequest
      //instance = new InvoiceContainerRequest();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'ContainerId'
    /// </summary>
    [Test]
    public void ContainerIdTest()
    {
      // TODO unit test for the property 'ContainerId'
    }

    /// <summary>
    ///   Test an instance of InvoiceContainerRequest
    /// </summary>
    [Test]
    public void InvoiceContainerRequestInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainerRequest
      //Assert.IsInstanceOfType<InvoiceContainerRequest> (instance, "variable 'instance' is a InvoiceContainerRequest");
    }
  }
}