/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainerUnlockRequest
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainerUnlockRequestTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainerUnlockRequest
    //private InvoiceContainerUnlockRequest instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainerUnlockRequest
      //instance = new InvoiceContainerUnlockRequest();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'ContainerId'
    /// </summary>
    [Test]
    public void ContainerIdTest()
    {
      // TODO unit test for the property 'ContainerId'
    }

    /// <summary>
    ///   Test an instance of InvoiceContainerUnlockRequest
    /// </summary>
    [Test]
    public void InvoiceContainerUnlockRequestInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainerUnlockRequest
      //Assert.IsInstanceOfType<InvoiceContainerUnlockRequest> (instance, "variable 'instance' is a InvoiceContainerUnlockRequest");
    }
  }
}