/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainerLockRequest
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainerLockRequestTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainerLockRequest
    //private InvoiceContainerLockRequest instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainerLockRequest
      //instance = new InvoiceContainerLockRequest();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'ContainerId'
    /// </summary>
    [Test]
    public void ContainerIdTest()
    {
      // TODO unit test for the property 'ContainerId'
    }

    /// <summary>
    ///   Test an instance of InvoiceContainerLockRequest
    /// </summary>
    [Test]
    public void InvoiceContainerLockRequestInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainerLockRequest
      //Assert.IsInstanceOfType<InvoiceContainerLockRequest> (instance, "variable 'instance' is a InvoiceContainerLockRequest");
    }

    /// <summary>
    ///   Test the property 'TimeoutSeconds'
    /// </summary>
    [Test]
    public void TimeoutSecondsTest()
    {
      // TODO unit test for the property 'TimeoutSeconds'
    }
  }
}