/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainerKeepAliveLockResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainerKeepAliveLockResponseTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainerKeepAliveLockResponse
    //private InvoiceContainerKeepAliveLockResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainerKeepAliveLockResponse
      //instance = new InvoiceContainerKeepAliveLockResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of InvoiceContainerKeepAliveLockResponse
    /// </summary>
    [Test]
    public void InvoiceContainerKeepAliveLockResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainerKeepAliveLockResponse
      //Assert.IsInstanceOfType<InvoiceContainerKeepAliveLockResponse> (instance, "variable 'instance' is a InvoiceContainerKeepAliveLockResponse");
    }

    /// <summary>
    ///   Test the property 'State'
    /// </summary>
    [Test]
    public void StateTest()
    {
      // TODO unit test for the property 'State'
    }
  }
}