/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainerLockResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainerLockResponseTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainerLockResponse
    //private InvoiceContainerLockResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainerLockResponse
      //instance = new InvoiceContainerLockResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of InvoiceContainerLockResponse
    /// </summary>
    [Test]
    public void InvoiceContainerLockResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainerLockResponse
      //Assert.IsInstanceOfType<InvoiceContainerLockResponse> (instance, "variable 'instance' is a InvoiceContainerLockResponse");
    }

    /// <summary>
    ///   Test the property 'State'
    /// </summary>
    [Test]
    public void StateTest()
    {
      // TODO unit test for the property 'State'
    }
  }
}