/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainersResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainersResponseTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainersResponse
    //private InvoiceContainersResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainersResponse
      //instance = new InvoiceContainersResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'From'
    /// </summary>
    [Test]
    public void FromTest()
    {
      // TODO unit test for the property 'From'
    }

    /// <summary>
    ///   Test an instance of InvoiceContainersResponse
    /// </summary>
    [Test]
    public void InvoiceContainersResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainersResponse
      //Assert.IsInstanceOfType<InvoiceContainersResponse> (instance, "variable 'instance' is a InvoiceContainersResponse");
    }

    /// <summary>
    ///   Test the property 'InvoiceContainers'
    /// </summary>
    [Test]
    public void InvoiceContainersTest()
    {
      // TODO unit test for the property 'InvoiceContainers'
    }

    /// <summary>
    ///   Test the property 'State'
    /// </summary>
    [Test]
    public void StateTest()
    {
      // TODO unit test for the property 'State'
    }

    /// <summary>
    ///   Test the property 'To'
    /// </summary>
    [Test]
    public void ToTest()
    {
      // TODO unit test for the property 'To'
    }
  }
}