/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing Invoice
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceTests
  {
    // TODO uncomment below to declare an instance variable for Invoice
    //private Invoice instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of Invoice
      //instance = new Invoice();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of Invoice
    /// </summary>
    [Test]
    public void InvoiceInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" Invoice
      //Assert.IsInstanceOfType<Invoice> (instance, "variable 'instance' is a Invoice");
    }

    /// <summary>
    ///   Test the property 'Pages'
    /// </summary>
    [Test]
    public void PagesTest()
    {
      // TODO unit test for the property 'Pages'
    }

    /// <summary>
    ///   Test the property 'PredictionResult'
    /// </summary>
    [Test]
    public void PredictionResultTest()
    {
      // TODO unit test for the property 'PredictionResult'
    }
  }
}