/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainerUnlockResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainerUnlockResponseTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainerUnlockResponse
    //private InvoiceContainerUnlockResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainerUnlockResponse
      //instance = new InvoiceContainerUnlockResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of InvoiceContainerUnlockResponse
    /// </summary>
    [Test]
    public void InvoiceContainerUnlockResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainerUnlockResponse
      //Assert.IsInstanceOfType<InvoiceContainerUnlockResponse> (instance, "variable 'instance' is a InvoiceContainerUnlockResponse");
    }

    /// <summary>
    ///   Test the property 'State'
    /// </summary>
    [Test]
    public void StateTest()
    {
      // TODO unit test for the property 'State'
    }
  }
}