/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing InvoiceContainerKeepAliveLockRequest
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class InvoiceContainerKeepAliveLockRequestTests
  {
    // TODO uncomment below to declare an instance variable for InvoiceContainerKeepAliveLockRequest
    //private InvoiceContainerKeepAliveLockRequest instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of InvoiceContainerKeepAliveLockRequest
      //instance = new InvoiceContainerKeepAliveLockRequest();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'ContainerId'
    /// </summary>
    [Test]
    public void ContainerIdTest()
    {
      // TODO unit test for the property 'ContainerId'
    }

    /// <summary>
    ///   Test an instance of InvoiceContainerKeepAliveLockRequest
    /// </summary>
    [Test]
    public void InvoiceContainerKeepAliveLockRequestInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" InvoiceContainerKeepAliveLockRequest
      //Assert.IsInstanceOfType<InvoiceContainerKeepAliveLockRequest> (instance, "variable 'instance' is a InvoiceContainerKeepAliveLockRequest");
    }

    /// <summary>
    ///   Test the property 'TimeoutSeconds'
    /// </summary>
    [Test]
    public void TimeoutSecondsTest()
    {
      // TODO unit test for the property 'TimeoutSeconds'
    }
  }
}