/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing MandatorResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class MandatorResponseTests
  {
    // TODO uncomment below to declare an instance variable for MandatorResponse
    //private MandatorResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of MandatorResponse
      //instance = new MandatorResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'ApiIdentifiers'
    /// </summary>
    [Test]
    public void ApiIdentifiersTest()
    {
      // TODO unit test for the property 'ApiIdentifiers'
    }

    /// <summary>
    ///   Test the property 'ApiKey'
    /// </summary>
    [Test]
    public void ApiKeyTest()
    {
      // TODO unit test for the property 'ApiKey'
    }

    /// <summary>
    ///   Test an instance of MandatorResponse
    /// </summary>
    [Test]
    public void MandatorResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" MandatorResponse
      //Assert.IsInstanceOfType<MandatorResponse> (instance, "variable 'instance' is a MandatorResponse");
    }

    /// <summary>
    ///   Test the property 'State'
    /// </summary>
    [Test]
    public void StateTest()
    {
      // TODO unit test for the property 'State'
    }
  }
}