/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing ModelObject
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class ModelObjectTests
  {
    // TODO uncomment below to declare an instance variable for ModelObject
    //private ModelObject instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of ModelObject
      //instance = new ModelObject();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of ModelObject
    /// </summary>
    [Test]
    public void ModelObjectInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" ModelObject
      //Assert.IsInstanceOfType<ModelObject> (instance, "variable 'instance' is a ModelObject");
    }
  }
}