/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing NeedForActionInvoiceContainerRequest
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class NeedForActionInvoiceContainerRequestTests
  {
    // TODO uncomment below to declare an instance variable for NeedForActionInvoiceContainerRequest
    //private NeedForActionInvoiceContainerRequest instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of NeedForActionInvoiceContainerRequest
      //instance = new NeedForActionInvoiceContainerRequest();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of NeedForActionInvoiceContainerRequest
    /// </summary>
    [Test]
    public void NeedForActionInvoiceContainerRequestInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" NeedForActionInvoiceContainerRequest
      //Assert.IsInstanceOfType<NeedForActionInvoiceContainerRequest> (instance, "variable 'instance' is a NeedForActionInvoiceContainerRequest");
    }
  }
}