/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing OcrResultResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class OcrResultResponseTests
  {
    // TODO uncomment below to declare an instance variable for OcrResultResponse
    //private OcrResultResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of OcrResultResponse
      //instance = new OcrResultResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'Message'
    /// </summary>
    [Test]
    public void MessageTest()
    {
      // TODO unit test for the property 'Message'
    }

    /// <summary>
    ///   Test an instance of OcrResultResponse
    /// </summary>
    [Test]
    public void OcrResultResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" OcrResultResponse
      //Assert.IsInstanceOfType<OcrResultResponse> (instance, "variable 'instance' is a OcrResultResponse");
    }

    /// <summary>
    ///   Test the property 'OcrResult'
    /// </summary>
    [Test]
    public void OcrResultTest()
    {
      // TODO unit test for the property 'OcrResult'
    }

    /// <summary>
    ///   Test the property 'State'
    /// </summary>
    [Test]
    public void StateTest()
    {
      // TODO unit test for the property 'State'
    }
  }
}