/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing Page
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class PageTests
  {
    // TODO uncomment below to declare an instance variable for Page
    //private Page instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of Page
      //instance = new Page();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test an instance of Page
    /// </summary>
    [Test]
    public void PageInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" Page
      //Assert.IsInstanceOfType<Page> (instance, "variable 'instance' is a Page");
    }

    /// <summary>
    ///   Test the property 'PageNo'
    /// </summary>
    [Test]
    public void PageNoTest()
    {
      // TODO unit test for the property 'PageNo'
    }

    /// <summary>
    ///   Test the property 'PreviewSrc'
    /// </summary>
    [Test]
    public void PreviewSrcTest()
    {
      // TODO unit test for the property 'PreviewSrc'
    }

    /// <summary>
    ///   Test the property 'Src'
    /// </summary>
    [Test]
    public void SrcTest()
    {
      // TODO unit test for the property 'Src'
    }
  }
}