/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing ReleasableInvoice
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class ReleasableInvoiceTests
  {
    // TODO uncomment below to declare an instance variable for ReleasableInvoice
    //private ReleasableInvoice instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of ReleasableInvoice
      //instance = new ReleasableInvoice();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'InvoiceId'
    /// </summary>
    [Test]
    public void InvoiceIdTest()
    {
      // TODO unit test for the property 'InvoiceId'
    }

    /// <summary>
    ///   Test the property 'PredictionResult'
    /// </summary>
    [Test]
    public void PredictionResultTest()
    {
      // TODO unit test for the property 'PredictionResult'
    }

    /// <summary>
    ///   Test an instance of ReleasableInvoice
    /// </summary>
    [Test]
    public void ReleasableInvoiceInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" ReleasableInvoice
      //Assert.IsInstanceOfType<ReleasableInvoice> (instance, "variable 'instance' is a ReleasableInvoice");
    }
  }
}