/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing ReleasableInvoiceResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class ReleasableInvoiceResponseTests
  {
    // TODO uncomment below to declare an instance variable for ReleasableInvoiceResponse
    //private ReleasableInvoiceResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of ReleasableInvoiceResponse
      //instance = new ReleasableInvoiceResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'Invoices'
    /// </summary>
    [Test]
    public void InvoicesTest()
    {
      // TODO unit test for the property 'Invoices'
    }

    /// <summary>
    ///   Test an instance of ReleasableInvoiceResponse
    /// </summary>
    [Test]
    public void ReleasableInvoiceResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" ReleasableInvoiceResponse
      //Assert.IsInstanceOfType<ReleasableInvoiceResponse> (instance, "variable 'instance' is a ReleasableInvoiceResponse");
    }

    /// <summary>
    ///   Test the property 'State'
    /// </summary>
    [Test]
    public void StateTest()
    {
      // TODO unit test for the property 'State'
    }
  }
}