/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing ReleaseInvoiceRequest
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class ReleaseInvoiceRequestTests
  {
    // TODO uncomment below to declare an instance variable for ReleaseInvoiceRequest
    //private ReleaseInvoiceRequest instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of ReleaseInvoiceRequest
      //instance = new ReleaseInvoiceRequest();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'InvoiceIds'
    /// </summary>
    [Test]
    public void InvoiceIdsTest()
    {
      // TODO unit test for the property 'InvoiceIds'
    }

    /// <summary>
    ///   Test an instance of ReleaseInvoiceRequest
    /// </summary>
    [Test]
    public void ReleaseInvoiceRequestInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" ReleaseInvoiceRequest
      //Assert.IsInstanceOfType<ReleaseInvoiceRequest> (instance, "variable 'instance' is a ReleaseInvoiceRequest");
    }
  }
}