/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing SaveInvoiceResponse
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class SaveInvoiceResponseTests
  {
    // TODO uncomment below to declare an instance variable for SaveInvoiceResponse
    //private SaveInvoiceResponse instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of SaveInvoiceResponse
      //instance = new SaveInvoiceResponse();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'InvoiceContainer'
    /// </summary>
    [Test]
    public void InvoiceContainerTest()
    {
      // TODO unit test for the property 'InvoiceContainer'
    }

    /// <summary>
    ///   Test an instance of SaveInvoiceResponse
    /// </summary>
    [Test]
    public void SaveInvoiceResponseInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" SaveInvoiceResponse
      //Assert.IsInstanceOfType<SaveInvoiceResponse> (instance, "variable 'instance' is a SaveInvoiceResponse");
    }

    /// <summary>
    ///   Test the property 'State'
    /// </summary>
    [Test]
    public void StateTest()
    {
      // TODO unit test for the property 'State'
    }
  }
}