/* 
 * BludeltaWebServiceAPI Hosted
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace IO.Swagger.Test
{
  /// <summary>
  ///   Class for testing UploadInvoiceContainerRequest
  /// </summary>
  /// <remarks>
  ///   This file is automatically generated by Swagger Codegen.
  ///   Please update the test case below to test the model.
  /// </remarks>
  [TestFixture]
  public class UploadInvoiceContainerRequestTests
  {
    // TODO uncomment below to declare an instance variable for UploadInvoiceContainerRequest
    //private UploadInvoiceContainerRequest instance;

    /// <summary>
    ///   Setup before each test
    /// </summary>
    [SetUp]
    public void Init()
    {
      // TODO uncomment below to create an instance of UploadInvoiceContainerRequest
      //instance = new UploadInvoiceContainerRequest();
    }

    /// <summary>
    ///   Clean up after each test
    /// </summary>
    [TearDown]
    public void Cleanup()
    {
    }

    /// <summary>
    ///   Test the property 'Description'
    /// </summary>
    [Test]
    public void DescriptionTest()
    {
      // TODO unit test for the property 'Description'
    }

    /// <summary>
    ///   Test the property 'File'
    /// </summary>
    [Test]
    public void FileTest()
    {
      // TODO unit test for the property 'File'
    }

    /// <summary>
    ///   Test the property 'Name'
    /// </summary>
    [Test]
    public void NameTest()
    {
      // TODO unit test for the property 'Name'
    }

    /// <summary>
    ///   Test an instance of UploadInvoiceContainerRequest
    /// </summary>
    [Test]
    public void UploadInvoiceContainerRequestInstanceTest()
    {
      // TODO uncomment below to test "IsInstanceOfType" UploadInvoiceContainerRequest
      //Assert.IsInstanceOfType<UploadInvoiceContainerRequest> (instance, "variable 'instance' is a UploadInvoiceContainerRequest");
    }
  }
}